Repository massalabs/massa, pull requests merged in 2021-11, with the labels that each got.

#1784 GitHub actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
  rust-toolchain
Labels: ci

#1798 Enable cargo caching on clippy & coverage stages and use minimal profile
  .coveralls.yml
  .github/workflows/ci.yml
  bors.toml
Labels: ci

#1799 Add status badges CI + Coverage to README
  .github/workflows/ci.yml
  README.md
Labels: ci

#1821 Fix code coverage ... again
  .github/workflows/ci.yml
Labels: ci

#1789 Make client input/output JSON with --json CLI option
  Cargo.lock
  api/src/lib.rs
  api/src/private.rs
  api/src/public.rs
  massa-client/Cargo.toml
  massa-client/src/cmds.rs
  massa-client/src/main.rs
  massa-client/src/repl.rs
  massa-client/src/rpc.rs
Labels: client

#1807 Updated concurrency.md
  docs/concurrency.md
Labels: review requested

#1834 Remove warnings from tests scenarios in consensus
  consensus/src/tests/block_factory.rs
  consensus/src/tests/scenario_block_creation.rs
  consensus/src/tests/scenario_roll.rs
  consensus/src/tests/scenarios106.rs
  consensus/src/tests/scenarios91_1.rs
  consensus/src/tests/scenarios91_2.rs
  consensus/src/tests/scenarios_basic.rs
  consensus/src/tests/scenarios_get_operations.rs
  consensus/src/tests/scenarios_header_check.rs
  consensus/src/tests/scenarios_incompatibilities.rs
  consensus/src/tests/scenarios_ledger.rs
  consensus/src/tests/scenarios_note_attack_attempt.rs
  consensus/src/tests/scenarios_operations_check.rs
  consensus/src/tests/scenarios_parents.rs
  consensus/src/tests/scenarios_pool_commands.rs
  consensus/src/tests/scenarios_pruning.rs
  consensus/src/tests/scenarios_reward_split.rs
  consensus/src/tests/scenarios_send_block.rs
  consensus/src/tests/scenarios_wishlist.rs
  consensus/src/tests/tools.rs
Labels: enhancement

#1832 Add mock of execution module in consensus
  consensus/src/tests/mock_execution_controller.rs
  consensus/src/tests/mod.rs
  consensus/src/tests/scenario_roll.rs
  consensus/src/tests/scenarios_ledger.rs
  consensus/src/tests/scenarios_note_attack_attempt.rs
  consensus/src/tests/scenarios_operations_check.rs
  consensus/src/tests/tools.rs
  execution/src/lib.rs
  execution/src/worker.rs
Labels: smart-contracts

#1842 Add a BORS badge
  README.md
Labels: ci

#1839 Use a `& 'static` ref of settings rather than cloning configuration at runtime across modules
  Cargo.lock
  api/src/lib.rs
  api/src/private.rs
  api/src/public.rs
  bootstrap/Cargo.toml
  bootstrap/src/lib.rs
  bootstrap/src/settings.rs
  bootstrap/src/tests/scenarios.rs
  bootstrap/src/tests/tools.rs
  consensus/src/consensus_controller.rs
  massa-client/Cargo.toml
  massa-client/src/main.rs
  massa-client/src/repl.rs
  massa-client/src/settings.rs
  massa-node/Cargo.toml
  massa-node/src/main.rs
  massa-node/src/node_config.rs
  massa-node/src/settings.rs
  models/src/api.rs
  pool/Cargo.toml
  pool/src/endorsement_pool.rs
  pool/src/lib.rs
  pool/src/operation_pool.rs
  pool/src/pool_controller.rs
  pool/src/pool_worker.rs
  pool/src/settings.rs
  pool/src/tests/mod.rs
  pool/src/tests/scenario.rs
  pool/src/tests/tools.rs
  protocol-exports/Cargo.toml
  protocol-exports/src/lib.rs
  protocol-exports/src/settings.rs
  protocol-exports/src/tests/tools.rs
  protocol-worker/Cargo.toml
  protocol-worker/src/protocol_controller.rs
  protocol-worker/src/tests/ask_block_scenarios.rs
  protocol-worker/src/tests/ban_nodes_scenarios.rs
  protocol-worker/src/tests/cache_scenarios.rs
  protocol-worker/src/tests/endorsements_scenarios.rs
  protocol-worker/src/tests/in_block_operations_scenarios.rs
  protocol-worker/src/tests/operations_scenarios.rs
  protocol-worker/src/tests/scenarios.rs
  protocol-worker/src/tests/tools.rs
Labels: node, refactoring, config

#1836 Updating readme and tutorials
  README.md
  docs/install.md
  docs/routability.md
  docs/run.md
  docs/staking.md
  docs/update.md
  docs/wallet.md
  docs/windows_install.md
Labels: documentation

#1853 Added logs to fix #1817
  consensus/src/block_graph.rs
Labels: review requested

#1859 Set-up a doc job in CI running on main
  .editorconfig
  .github/workflows/ci.yml
Labels: ci

#1861 Fix #1824: error should be also handled in JSON format
  massa-client/src/cmds.rs
  massa-client/src/main.rs
  massa-client/src/repl.rs
Labels: client

#1869 Fix `doc` stage in CI
  .github/workflows/ci.yml
Labels: ci

#1870 Add link to code documentation in README
  README.md
Labels: documentation
