Repository massalabs/massa, pull requests merged in 2021-12, with the labels that each got.

#1881 Doc/pos
  consensus/src/pos.rs
Labels: review requested

#1875 Doc/block graph
  consensus/src/block_graph.rs
Labels: review requested

#1877 Doc/ledger
  consensus/src/ledger.rs
  models/src/ledger.rs
Labels: review requested

#1882 Doc/todo
  api/src/lib.rs
  bootstrap/src/lib.rs
  consensus/src/block_graph.rs
  consensus/src/ledger.rs
  consensus/src/tests/scenario_roll.rs
  consensus/src/tests/scenarios_ledger.rs
  massa-client/src/main.rs
  massa-client/src/tests/tools.rs
  massa-node/src/main.rs
  models/src/slot.rs
  network/src/network_worker.rs
  network/src/node_worker.rs
  wallet/src/lib.rs
Labels: review requested

#1855 Fix #1146 added when episode ends client command.
  consensus/src/consensus_worker.rs
  massa-client/src/cmds.rs
  models/src/version.rs
  time/src/lib.rs
Labels: review requested

#1896 Rename `darwin` to `macos` in release artifacts
  .github/workflows/cd.yml
Labels: p1, ci

#1893 Improve extended wallet indentation.
  models/src/api.rs
Labels: review requested

#1906 `s/endorsment/endorsement`
  bootstrap/src/tests/tools.rs
  consensus/src/block_graph.rs
  consensus/src/ledger.rs
  consensus/src/tests/tools.rs
  massa-node/src/main.rs
  models/src/block.rs
  models/src/clique.rs
  models/src/context.rs
  models/src/endorsement.rs
  models/src/slot.rs
  network/src/messages.rs
  network/src/tests/tools.rs
  pool/src/operation_pool.rs
  protocol-exports/src/tests/tools.rs
Labels: refactoring

#1918 Fix warning in massa-hash
  bootstrap/src/client_binder.rs
  bootstrap/src/server_binder.rs
  bootstrap/src/tests/tools.rs
  consensus/src/block_graph.rs
  consensus/src/consensus_worker.rs
  consensus/src/pos.rs
  consensus/src/tests/block_factory.rs
  consensus/src/tests/scenario_block_creation.rs
  consensus/src/tests/scenarios91_1.rs
  consensus/src/tests/scenarios91_2.rs
  consensus/src/tests/scenarios_basic.rs
  consensus/src/tests/scenarios_endorsements.rs
  consensus/src/tests/scenarios_note_attack_attempt.rs
  consensus/src/tests/scenarios_reward_split.rs
  consensus/src/tests/tools.rs
  massa_hash/src/hash.rs
  models/src/address.rs
  models/src/block.rs
  models/src/clique.rs
  models/src/endorsement.rs
  models/src/operation.rs
  models/src/slot.rs
  network/src/handshake_worker.rs
  network/src/network_worker.rs
  network/src/tests/scenarios.rs
  network/src/tests/tools.rs
  pool/src/operation_pool.rs
  pool/src/tests/tools.rs
  protocol-exports/src/tests/tools.rs
  protocol-worker/src/protocol_controller.rs
  protocol-worker/src/tests/in_block_operations_scenarios.rs
  signature/src/signature_impl.rs
  wallet/src/lib.rs
Labels: refactoring

#1908 document hhasher
  models/src/hhasher.rs
Labels: documentation

#1905 Include hacking `.md` inside `cargo doc` output
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  consensus/endorsements.md
  consensus/pos.md
  consensus/src/lib.rs
  consensus/src/pos.rs
  docs/api.md
  docs/concurrency.md
  docs/faq.md
  docs/install.md
  docs/routability.md
  docs/run.md
  docs/staking.md
  docs/transaction.md
  docs/update.md
  massa-node/storage/info.md
  protocol-worker/src/lib.rs
Labels: documentation

#1953 Fix broken links in README
  README.md
Labels: documentation

#1957 Make `massa-node` & `massa-client` config loading behave the same way
  Cargo.lock
  massa-client/Cargo.toml
  massa-client/src/settings.rs
  massa-node/Cargo.toml
  massa-node/src/settings.rs
Labels: client

#2017 Add unported changes from add_vm_to_execution
  massa-consensus/src/ledger.rs
  massa-execution/src/sce_ledger.rs
  massa-execution/src/tests/scenarios_mandatories.rs
  massa-models/src/amount.rs
  massa-models/src/lib.rs
  massa-node/src/main.rs
Labels: smart-contracts

#2042 repair cautious bassoon
  massa-consensus/src/block_graph.rs
  massa-execution/src/worker.rs
  massa-models/src/address.rs
Labels: smart-contracts

#2040 Read only execution
  massa-execution/Cargo.toml
  massa-execution/read-only.md
  massa-execution/src/controller.rs
  massa-execution/src/tests/scenarios_mandatories.rs
  massa-execution/src/types.rs
  massa-execution/src/vm.rs
  massa-execution/src/worker.rs
  massa-models/src/execution.rs
  massa-models/src/lib.rs
Labels: smart-contracts

#2054 Correct tests
  massa-client/src/tests/mod.rs
  massa-client/src/tests/scenarios.rs
  massa-consensus/src/tests/scenario_block_creation.rs
  massa-consensus/src/tests/scenario_roll.rs
  massa-time/src/lib.rs
Labels: bug
