Repository massalabs/massa, pull requests merged in 2022-01, with the labels that each got.

#2052 Read only execution api
  Cargo.lock
  massa-api/Cargo.toml
  massa-api/src/error.rs
  massa-api/src/lib.rs
  massa-api/src/private.rs
  massa-api/src/public.rs
  massa-models/src/execution.rs
  massa-node/src/main.rs
Labels: smart-contracts

#2058 repair test reward split
  massa-consensus/src/tests/scenarios_reward_split.rs
Labels: bug, test

#2049 Only test stop_node if feature `local` activated
  massa-client/src/tests/mod.rs
  massa-client/src/tests/scenarios.rs
  massa-consensus/src/tests/scenario_block_creation.rs
  massa-consensus/src/tests/scenario_roll.rs
  massa-consensus/src/tests/scenarios_reward_split.rs
  massa-time/src/lib.rs
Labels: enhancement

#2059 Transfet coins abi
  Cargo.lock
  massa-execution/Cargo.toml
  massa-execution/src/interface_impl.rs
Labels: smart-contracts

#2068 leave more time to init test
  massa-consensus/src/tests/scenario_roll.rs
  massa-consensus/src/tests/scenarios106.rs
Labels: bug

#2082 Repair exec loop
  massa-execution/src/worker.rs
Labels: bug, smart-contracts

#2083 log generated execution events
  massa-execution/src/interface_impl.rs
Labels: smart-contracts

#2087 repair and test executesc serialization
  massa-models/src/operation.rs
Labels: smart-contracts

#2093 Execution: impl get_balance on interface
  Cargo.lock
  massa-execution/Cargo.toml
  massa-execution/src/interface_impl.rs
Labels: smart-contracts

#2092 Correct VM history
  massa-execution/src/vm.rs
  massa-execution/src/worker.rs
  massa-models/src/timeslots.rs
Labels: smart-contracts

#2096 move sc logs to debug level
  massa-execution/src/interface_impl.rs
Labels: smart-contracts

#2097 update sc-runtime to v0.2.6
  massa-execution/Cargo.toml
Labels: smart-contracts

#2098 update runtime sc
  Cargo.lock
  massa-execution/Cargo.toml
Labels: smart-contracts

#2099 repair consensus log
  massa-consensus/src/consensus_worker.rs
Labels: bug, consensus

#2100 update runtime version
  Cargo.lock
  massa-execution/Cargo.toml
Labels: smart-contracts

#2102 disable non sce final exec
  massa-consensus/src/consensus_worker.rs
  massa-execution/src/worker.rs
Labels: smart-contracts

#2141 Temporary set a version of rust
  .github/workflows/cd.yml
  .github/workflows/ci-light.yml
  .github/workflows/ci.yml
Labels: bug

#2147 Temporary ignore UT since repairing it
  massa-consensus/src/tests/scenario_roll.rs
Labels: bug

#2137 repair SCE ledger updates
  massa-execution/src/interface_impl.rs
  massa-execution/src/sce_ledger.rs
Labels: breaking

#2150 Create stale.yml
  .github/workflows/stale.yml
Labels: documentation

#2114 Update cd.yml
  .github/workflows/cd.yml
Labels: refactoring

#2175 Fix: `wallet_remove_addresses` does not update wallet file
  massa-client/src/cmds.rs
  massa-wallet/src/lib.rs
Labels: bug

#2155 Revert the version of Rust fixed
  .github/workflows/ci-light.yml
  .github/workflows/ci.yml
Labels: refactoring

#2139 Add initial peers separated from the peer file.
  .gitignore
  massa-network/src/network_controller.rs
  massa-network/src/peer_info_database.rs
  massa-network/src/settings.rs
  massa-network/src/tests/tools.rs
  massa-node/base_config/config.toml
  massa-node/base_config/initial_peers.json
  massa-node/storage/peers.json
Labels: refactoring

#2198 Add the `RELEASE_VERSION` in the artifacts names
  .github/workflows/cd.yml
Labels: ci

#2209 Readme updated with latest links
  README.md
Labels: documentation

#2128 Deployment script :rainbow:
  .github/workflows/cd.yml
Labels: refactoring
