Repository massalabs/massa, pull requests merged in 2022-03, with the labels that each got.

#2251 Path completion on the client REPL.
  Cargo.lock
  massa-client/Cargo.toml
  massa-client/src/repl.rs
Labels: client

#2363 Implement signed struct.
  massa-api/src/lib.rs
  massa-api/src/private.rs
  massa-api/src/public.rs
  massa-bootstrap/src/tests/tools.rs
  massa-client/src/cmds.rs
  massa-consensus-exports/src/commands.rs
  massa-consensus-exports/src/consensus_controller.rs
  massa-consensus-worker/endorsements.md
  massa-consensus-worker/src/consensus_worker.rs
  massa-consensus-worker/src/tests/block_factory.rs
  massa-consensus-worker/src/tests/mock_protocol_controller.rs
  massa-consensus-worker/src/tests/scenario_block_creation.rs
  massa-consensus-worker/src/tests/scenario_roll.rs
  massa-consensus-worker/src/tests/scenarios_endorsements.rs
  massa-consensus-worker/src/tests/scenarios_get_operations.rs
  massa-consensus-worker/src/tests/scenarios_pool_commands.rs
  massa-consensus-worker/src/tests/scenarios_reward_split.rs
  massa-consensus-worker/src/tests/test_block_graph.rs
  massa-consensus-worker/src/tests/tools.rs
  massa-execution-worker/src/execution.rs
  massa-graph/src/block_graph.rs
  massa-graph/src/export_active_block.rs
  massa-graph/src/ledger.rs
  massa-models/src/api.rs
  massa-models/src/block.rs
  massa-models/src/composite.rs
  massa-models/src/endorsement.rs
  massa-models/src/lib.rs
  massa-models/src/operation.rs
  massa-models/src/signed.rs
  massa-network/src/messages.rs
  massa-network/src/network_controller.rs
  massa-network/src/network_worker.rs
  massa-network/src/node_worker.rs
  massa-network/src/tests/scenarios.rs
  massa-network/src/tests/tools.rs
  massa-pool/src/endorsement_pool.rs
  massa-pool/src/operation_pool.rs
  massa-pool/src/pool_controller.rs
  massa-pool/src/pool_worker.rs
  massa-pool/src/tests/mock_protocol_controller.rs
  massa-pool/src/tests/operation_pool_tests.rs
  massa-pool/src/tests/scenario.rs
  massa-pool/src/tests/tools.rs
  massa-proof-of-stake-exports/src/lib.rs
  massa-protocol-exports/src/protocol_controller.rs
  massa-protocol-exports/src/tests/mock_network_controller.rs
  massa-protocol-exports/src/tests/tools.rs
  massa-protocol-worker/src/protocol_worker.rs
  massa-protocol-worker/src/tests/ask_block_scenarios.rs
  massa-protocol-worker/src/tests/ban_nodes_scenarios.rs
  massa-protocol-worker/src/tests/endorsements_scenarios.rs
  massa-protocol-worker/src/tests/in_block_operations_scenarios.rs
  massa-protocol-worker/src/tests/operations_scenarios.rs
  massa-protocol-worker/src/tests/scenarios.rs
  massa-sdk/src/lib.rs
  massa-wallet/src/lib.rs
Labels: review requested

#2304 Use shared storage in protocol
  massa-consensus-worker/src/consensus_worker.rs
  massa-graph/src/block_graph.rs
  massa-network/src/network_worker.rs
  massa-network/src/node_worker.rs
  massa-node/src/main.rs
  massa-protocol-exports/src/lib.rs
  massa-protocol-exports/src/protocol_controller.rs
  massa-protocol-worker/src/protocol_worker.rs
Labels: review requested, storage

#2305 Use shared storage in Network
  massa-consensus-worker/src/consensus_worker.rs
  massa-graph/src/block_graph.rs
  massa-models/src/storage.rs
  massa-network/src/binders.rs
  massa-network/src/handshake_worker.rs
  massa-network/src/messages.rs
  massa-network/src/network_controller.rs
  massa-network/src/network_worker.rs
  massa-network/src/node_worker.rs
  massa-node/src/main.rs
  massa-protocol-exports/src/lib.rs
  massa-protocol-exports/src/protocol_controller.rs
  massa-protocol-worker/src/protocol_worker.rs
Labels: review requested, storage

#2322 Execution: use shared storage
  massa-consensus-worker/src/consensus_worker.rs
  massa-execution-exports/src/controller_traits.rs
  massa-execution-worker/src/controller.rs
  massa-execution-worker/src/execution.rs
  massa-execution-worker/src/worker.rs
  massa-graph/src/block_graph.rs
  massa-node/src/main.rs
Labels: review requested, storage

#2359 More SCE ledger info in api and client.
  massa-api/src/public.rs
  massa-models/src/api.rs
Labels: review requested

#2383 Fix tests shared storage
  Cargo.lock
  massa-bootstrap/src/tests/tools.rs
  massa-consensus-exports/src/consensus_controller.rs
  massa-consensus-worker/Cargo.toml
  massa-consensus-worker/src/consensus_worker.rs
  massa-consensus-worker/src/tests/mock_protocol_controller.rs
  massa-consensus-worker/src/tests/scenario_block_creation.rs
  massa-consensus-worker/src/tests/scenario_roll.rs
  massa-consensus-worker/src/tests/scenarios_get_operations.rs
  massa-consensus-worker/src/tests/scenarios_ledger.rs
  massa-consensus-worker/src/tests/scenarios_note_attack_attempt.rs
  massa-consensus-worker/src/tests/scenarios_pool_commands.rs
  massa-consensus-worker/src/tests/test_block_graph.rs
  massa-consensus-worker/src/tests/tools.rs
  massa-execution-exports/src/test_exports/mock.rs
  massa-graph/src/block_graph.rs
  massa-graph/src/export_active_block.rs
  massa-models/Cargo.toml
  massa-models/src/storage.rs
  massa-network/src/binders.rs
  massa-network/src/messages.rs
  massa-network/src/network_controller.rs
  massa-network/src/network_worker.rs
  massa-network/src/node_worker.rs
  massa-network/src/tests/scenarios.rs
  massa-network/src/tests/tools.rs
  massa-protocol-exports/src/lib.rs
  massa-protocol-exports/src/protocol_controller.rs
  massa-protocol-exports/src/tests/mock_network_controller.rs
  massa-protocol-exports/src/tests/tools.rs
  massa-protocol-worker/src/protocol_worker.rs
  massa-protocol-worker/src/tests/ask_block_scenarios.rs
  massa-protocol-worker/src/tests/ban_nodes_scenarios.rs
  massa-protocol-worker/src/tests/cache_scenarios.rs
  massa-protocol-worker/src/tests/endorsements_scenarios.rs
  massa-protocol-worker/src/tests/operations_scenarios.rs
  massa-protocol-worker/src/tests/scenarios.rs
  massa-protocol-worker/src/tests/tools.rs
Labels: storage

#2297 Refactor to prepare whitelist peers
  Cargo.lock
  massa-network-exports/Cargo.toml
  massa-network-exports/src/error.rs
  massa-network-exports/src/lib.rs
  massa-network-exports/src/peers.rs
  massa-network-exports/src/settings.rs
  massa-network-worker/Cargo.toml
  massa-network-worker/src/network_cmd_impl.rs
  massa-network-worker/src/peer_info_database.rs
  massa-network-worker/src/tests/scenarios.rs
  massa-network-worker/src/tests/test_peer_info_database.rs
  massa-network-worker/src/tests/tools.rs
  massa-node/base_config/config.toml
  massa-node/base_config/initial_peers.json
  massa-node/src/tests/config.toml
Labels: review requested

#2437 Remove deserialization of phantom field.
  massa-models/src/signed.rs
Labels: p1

#2430 Massa async pool
  massa-async-pool/Cargo.toml
  massa-async-pool/src/bootstrap.rs
  massa-async-pool/src/changes.rs
  massa-async-pool/src/config.rs
  massa-async-pool/src/lib.rs
  massa-async-pool/src/message.rs
  massa-async-pool/src/pool.rs
  massa-async-pool/src/test_exports/bootstrap.rs
  massa-async-pool/src/test_exports/config.rs
  massa-async-pool/src/test_exports/mod.rs
  massa-async-pool/src/tests/mod.rs
Labels: p1

#2456 repair bug 2386
  massa-execution-worker/src/execution.rs
  massa-execution-worker/src/worker.rs
Labels: p1
